### ISSUE TITLE
Pay with Bank option is not showing

### ISSUE THREAD

**Issue by mittalkamal29** [just1and0/React-Native-Paystack-WebView#110]
**Describe the bug**
I am using sdk and try to pay with all three optiion but pay with bank option is not showing while it is bank option is on from paystack dashboard -> settings -> preferences. 

My code as below:
  

> <Paystack
>           paystackKey="---------"
>           billingEmail="-----------"
>           amount={"25.00"}
>           channels={["bank", "card", "ussd"]}
>           currency={"NGN"}
>           onCancel={(e) => {
>             // handle response here
>           }}
>           onSuccess={(res) => {
>             // handle response here
>           }}
>           autoStart={true}
>         />
> 

**Screenshots**
![Uploading Simulator Screen Shot - iPhone 13 - 2022-06-22 at 18.13.53.png…]()

**Additional context**
Can you suggest how to get the the option?

Thanks

**Comment by just1and0** [comment]
hey, @mittalkamal29  `pay with. bank` is not supported on the inline-js which is what this package is built on top of. Here is a list of the supported channels for inline > ['card', 'bank', 'ussd', 'qr', 'eft', 'mobile_money', 'bank_transfer', ‘apple_pay’]
