### ISSUE TITLE
Kenya Currency and Mpesa

### ISSUE THREAD

**Issue by sydiaplatform** [just1and0/React-Native-Paystack-WebView#113]
Hello there,

1. I would be great to see an option to input the currency, I managed to do this by removing the currency on line 28 on the paystack.js file and adding it to the <Paystack /> element.

2. I would be great to have an option for 'channel' under the <Paystack /> element. Right now I had to remove ['card'] from line 28 on the paystack.js file for it to pull all available payment methods from the Paystack dashboard.

Cheers!

**Comment by gray-adeyi** [comment]
Hi! try out this package. It's not yet a major release but it supports typescript and other JavaScript runtime like bun and Deno https://www.npmjs.com/package/@gray-adeyi/paystack-sdk

**Comment by just1and0** [comment]
![image](https://github.com/user-attachments/assets/82b1a7e8-6c90-4460-a272-1e7da5cff346)

Currently we support not just NGN in currency and also channels has more options. 

Closing this.
