### ISSUE TITLE
Macbook M1 Issue

### ISSUE THREAD

**Issue by chrisedington** [just1and0/React-Native-Paystack-WebView#114]
I had issues getting the project running on a Macbook Pro M1.

```
Undefined symbol: _RCTRegisterModule
```

I had to make the following change for it to work - maybe it'll help someone:

```
node_modules/react-native-paystack-webview/react-native-paystack-webview.podspec
-  s.dependency 'React'
+  s.dependency 'React-Core'
```

Make sure to do a `pod install` afterwards.

**Comment by just1and0** [comment]
Thanks for sharing. We revamped the latest version and you wont have this issue again.
