### ISSUE TITLE
Can't install via npm 

### ISSUE THREAD

**Issue by mojeedoyedeji** [just1and0/React-Native-Paystack-WebView#12]
Hi, I am issues with install this npm package. The error message can be found below

![Selection_001](https://user-images.githubusercontent.com/10332215/77258190-0695f900-6c8a-11ea-99ea-8273396d19b7.png)

**Comment by tons613** [comment]
install with yarn
`yarn add react-native-paystack-webview`

**Comment by just1and0** [comment]
Hi @mojeedoyedeji, 

I just ran the command and it works on my system, I will suggest you use yarn but just before you do that, try to update the package to v3.0.3, I have made some changes that should solve this issue.

<img width="1138" alt="Screenshot 2020-03-23 at 07 36 26" src="https://user-images.githubusercontent.com/17249207/77288934-2f91aa80-6cd9-11ea-9cef-d9c0829ba153.png">
