### ISSUE TITLE
Payment via Bank Card with Bank Authentication

### ISSUE THREAD

**Issue by mittalkamal29** [just1and0/React-Native-Paystack-WebView#124]
**Describe the bug**
I am facing issue with production while in demo/staging, it is working fine. 
When i try to pay with card, it try to open bank authentication screen but after some time, it show screen which says, close the screen to continue without any button so there is no way to close the screen and complete the process. 

**To Reproduce**
1. open Paystack pyment view
2. Add card infomation
3. Ask for bank authentication
4. See error screen

**Expected behavior**
Should be open bank authentication screen.

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/3142539/205839593-39c7d7e1-2b61-47aa-9137-0b25cdb9eb51.jpg)

**Comment by codexjoshy** [comment]
I have been having this issue too for a while now, i hope it is resolved soon.

**Comment by renderappdev** [comment]
Hello. Were you able to resolve this issue. We are having this same issue on our end too.

**Comment by mopilo** [comment]
@just1and0 this happens on Production. can you take a look?

**Comment by just1and0** [comment]
Hello, can you try react-native-paystack-webview@4.0.4 and confirm if you still have this issue?

**Comment by just1and0** [comment]
closing stale issue.
