### ISSUE TITLE
react-native-paystack on Android only Keeps asking for pin again and again (Live keys)

### ISSUE THREAD

**Issue by reacttest9** [just1and0/React-Native-Paystack-WebView#127]
**Describe the bug**

**To Reproduce**
1. Go to Payment Screen
2. Click on make payment
3. when user enters the pin then it will keep asking pin again and again

**Expected behavior**
After the pin it should take the pin and make the payment, but it keeps asking me for pin again and again

This is the repo link
https://github.com/reacttest9/SmartCity

**Screenshots**
![IMG-20221118-WA0008](https://user-images.githubusercontent.com/103558558/207049235-9ca74548-2ad5-462e-b745-19e852d55912.jpg)
![IMG-20221118-WA0006](https://user-images.githubusercontent.com/103558558/207049250-7a24c84b-7e78-4c9a-93f7-9e128dff742c.jpg)

**Comment by just1and0** [comment]
Resolved on latest release.
