### ISSUE TITLE
Create a subscription with this package

### ISSUE THREAD

**Issue by Ayobamiu** [just1and0/React-Native-Paystack-WebView#128]
Allow users to specify an optional "plan" parameter so that the transaction can be used to create a subscription.

**Additional context**
https://paystack.com/docs/payments/subscriptions#create-a-subscription

**Comment by gray-adeyi** [comment]
Hi! this is not a react native package but try out this package. It's not yet a major release but it supports typescript and other JavaScript runtime like bun and Deno https://www.npmjs.com/package/@gray-adeyi/paystack-sdk

**Comment by just1and0** [comment]
Available on version 4.3.0
