### ISSUE TITLE
Can you please add a metadata as a prop to the Paystack component

### ISSUE THREAD

**Issue by everbliss7** [just1and0/React-Native-Paystack-WebView#132]
**Is your feature request related to a problem? Please describe.**
I need to add metadata to the request body so that Paystack can record the purchase service/products information

**Describe the solution you'd like**
add a metadata prop to the Paystack component

**Describe alternatives you've considered**
No Alternative

**Comment by sleekLancelot** [comment]
I also need this right now, does anyone know of any alternative to handling payment in react native using paystack?

**Comment by just1and0** [comment]
@sleekLancelot  @everbliss7 fancy opening a PR and adding this feature ? It would be awesome if you help improve this package :)

**Comment by just1and0** [comment]
Available on latest release.
