### ISSUE TITLE
The reference does not match when trying to verify the transaction

### ISSUE THREAD

**Issue by Thomasosho** [just1and0/React-Native-Paystack-WebView#137]
**Describe the bug**
response.data.transactionRef.reference is generated when a successful transaction takes place. When i try verifying using paystack's API, i get an error stating that it does not match.

**Expected behavior**
It's supposed to verify my payment.

**Upon submitting the reference to verify payment**
```
transactionId: response.data.transactionRef.reference.toString(),
paymentGateway: 'paystack',
```
this is what i get
```
Transaction record not found
<img width="347" alt="Screenshot 2023-06-18 at 23 05 05" src="https://github.com/just1and0/React-Native-Paystack-WebView/assets/11132861/1a5e0eac-e96c-49bd-b95d-f5c2aec5e45f">
```

**Comment by opmat** [comment]
Hi @Thomasosho 
Can you explain how you are performing the verification? and probably upload a new screenshot as the one you uploaded is not showing

**Comment by just1and0** [comment]
Closing as it's been inactive for a year.
