### ISSUE TITLE
Could not determine the dependencies of task ':react-native-paystack-webview:bundleLibCompileToJarDebug'

### ISSUE THREAD

**Issue by Felix-Asante** [just1and0/React-Native-Paystack-WebView#139]
I am trying to generate a debug apk for an app I am building that uses React-native-paystack-webview.  For some reason when try to build with gradle I get this error **"Could not determine the dependencies of task ':react-native-paystack-webview:bundleLibCompileToJarDebug "** 

please let me know what I am doing wrong and how I can fix it

**I am using**
 "react-native-paystack-webview": "^4.0.3",
 "react-native-webview": "^13.6.0",
"react-native": "0.72.1",

**Comment by hameed-ijadunola** [comment]
@Felix-Asante I'm experiencing the same issue.
Did you later resolve this issue?

**Comment by oluwatoba1** [comment]
This might be long overdue, I also encountered this issue

Add `kotlinVersion = "1.8.22"` inside build.ext block in android/build.gradle file

Example:
`ext {
buildToolsVersion = "33.0.0"
minSdkVersion = 21
compileSdkVersion = 33
targetSdkVersion = 33

    ndkVersion = "23.1.7779620"
    kotlinVersion = "1.8.22" 
}`

**Comment by just1and0** [comment]
@Felix-Asante is this still the case with react-native-paystack-webview@4.0.4 ?

**Comment by oluwatoba1** [comment]
I will bump the version and let you know

**Comment by uhembenelson** [comment]
Has anybody found a way around this error?

**Comment by oluwatoba1** [comment]
Are you still having this issue on 4.0.4?

**Comment by uhembenelson** [comment]
@oluwatoba1  No this solution works for me

 ext {
        ...
        ndkVersion = "23.1.7779620"
        kotlinVersion = "1.8.22"
    }

**Comment by just1and0** [comment]
Hello, can you please update your package to the latest and try again ?
