### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by zictechng** [just1and0/React-Native-Paystack-WebView#144]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I am having same issue in my react native expo app. I tested it last month February 1, 2024  but today is not working anymore

**Comment by just1and0** [comment]
@zictechng can you retry this with v4.0.4 and confirm if this is still the same case?

**Comment by zictechng** [comment]
> @zictechng can you retry this with v4.0.4 and confirm if this is still the same case?

Please, what did you mean? I can't get you correctly. 
Do you mean, I should change the version of the react-native-paystack-webview ?
But, currently it has "^4.0.3" so, what do you think I can do pls? Thanks

**Comment by stashngr** [comment]
I had the same experience pls is there any fix or work around for this?

**Comment by zictechng** [comment]
You can check again, I think it is working now. I contacted them so I think
they have fixed it because they later got back to me to re-try it and I did
and it was working fine.

So, you can try it again too.
Thank you.
*Zictech*

Web App Development, Internet Marketing, Website Development, School
Management System/Portal, Software Development, Training, Capacity Build
Training Program and General IT Consultancy.

*Quick Contact*
No. 4 Chilloville Avenue, Ikota Road, Royal Estate Lekki-Ajah Lagos.

#1 Dan-Sani House by Top Medical Road Junction, Along Paiko Road
Tunga Minna,
Niger State, Nigeria.
 *+2348037-250-238*
www.zictech-ng.com

**Comment by mosoakinyemi** [comment]
Closing this as it’s fixed.
