### ISSUE TITLE
Jest Unit Testing

### ISSUE THREAD

**Issue by olawalejuwonm** [just1and0/React-Native-Paystack-WebView#157]
I got this error when running jest on a project that use this library
![image](https://github.com/just1and0/React-Native-Paystack-WebView/assets/52759812/8da243dc-3951-41d2-89cf-d6757a9a32e5)

**Comment by just1and0** [comment]
Fixed in latest release

**Comment by olawalejuwonm** [comment]
Happy to see this project come alive again
