### ISSUE TITLE
Webview not working on Android currently

### ISSUE THREAD

**Issue by Madflows** [just1and0/React-Native-Paystack-WebView#163]
**Describe the bug**
Using the library on expo go with android returns this, even though it works perfectly on ios.

![IMG_6886](https://github.com/just1and0/React-Native-Paystack-WebView/assets/57838473/c674e1a6-928f-466e-888c-9b23e46efd62)

**Comment by ColTheDeveloper** [comment]
i'm also facing the same issue ,i don't know if you later find a way around it

**Comment by ColTheDeveloper** [comment]
@just1and0

**Comment by Madflows** [comment]
Nah, not fixed yet

**Comment by opmat** [comment]
@Madflows can you give more explanation of what you did and probably provide code snippet? You can also provide more information of your development environment and the library version you are using

**Comment by just1and0** [comment]
I am closing this as we just released a net version. Should you have this issue we can re-open.

**Comment by just1and0** [comment]
resolved on version 4.2.0

**Comment by nmasi322** [comment]
This bug appears in v4.6.7
