### ISSUE TITLE
Need a way to route back to app if modal didn't open successfully

### ISSUE THREAD

**Issue by cardiscardis** [just1and0/React-Native-Paystack-WebView#165]
Each time the paystack opens canGoBack is false and the app cannot route back to the app like it is in Flutterwave. The implication is that if the modal fails to connect to paystack gateway and brings something like net::err_blocked_by_response instead of the paystack payment UI, the app becomes stuck until one closes the app and relaunches it. This is not good UX

**Describe the solution you'd like**
There should be a way to snap out of the paystack modal if the modal fails at every point.

**Describe alternatives you've considered**
An alternative is to always make sure the modal launches the paystack payment UI, that can probably be some local components

**Comment by just1and0** [comment]
Hello, thanks for raising this.

I do feel a good approach to resolving this would be to expose a new component that doesn't show the webview in a modal. This way, people will have more control over the webview and even make their own modal component that better aligns with their use-case.

**Comment by just1and0** [comment]
Available on version 4.2.0
