### ISSUE TITLE
SDK Integration with PwT (PayWithTransfer)

### ISSUE THREAD

**Issue by UdumiziSolomon** [just1and0/React-Native-Paystack-WebView#167]
**Can we have PwT (Pay with Transfer) added to the channels where a temporary account is generated for users to pay into**

**Comment by hushjozy** [comment]
please, this would be nice

**Comment by gray-adeyi** [comment]
Hi! while this is not a package for react native, try out this package. It's not yet a major release but it supports typescript and other JavaScript runtime like bun and Deno https://www.npmjs.com/package/@gray-adeyi/paystack-sdk

**Comment by just1and0** [comment]
@opmat would you like to update the docs with this new item so folks know it's available?

**Comment by just1and0** [comment]
available on version 4.1.2
