### ISSUE TITLE
I got this error 'RNCWebViewModule' could not be found.

### ISSUE THREAD

**Issue by mrkendrick** [just1and0/React-Native-Paystack-WebView#168]
![2024-08-18-024141_1920x1080_scrot](https://github.com/user-attachments/assets/0bac73a1-889c-44e5-901d-9ba23133982a)

react-native-webview: v13.8.6
react-native-paystack-webview: v4.1.4
expo: v51.0.26

**Comment by just1and0** [comment]
@mrkendrick I see you are running this on EXPO. could you try updating to v4.0.5 and use the `npx expo install react-native-webview` to install web view instead. 

Let me know if that works.
