### ISSUE TITLE
onCancle callback bug

### ISSUE THREAD

**Issue by GideonAgboba** [just1and0/React-Native-Paystack-WebView#17]
react-native-paystack-webview does not run onSuccess function after successful transaction...

please observe the code below...
<PaystackWebView
showPayButton={false}
currency="NGN"
channels="card"
paystackKey="pk_test_****************************"
amount={amount}
billingEmail={email}
billingMobile={phone}
billingName={fullname}
ActivityIndicatorColor="green"
onSuccess={(tranRef) => {
// do something...
console.log('transaction ref', tranRef);
}}
onCancel={(res) => {
// show a message (issue here)
}}
autoStart={false}
ref={childRef}
/>
Note: this code inits the popup window...
i don't know what am doing wrong here. But if the payment is successful or not only the onCancel function runs...

![WhatsApp Image 2020-05-02 at 2 39 58 AM](https://user-images.githubusercontent.com/33206022/81138708-cf1c9c80-8f17-11ea-80b0-737363cba3e6.jpeg)
![WhatsApp Image 2020-05-02 at 2 39 58 AM (1)](https://user-images.githubusercontent.com/33206022/81138723-d643aa80-8f17-11ea-861e-4198e0fa167c.jpeg)
![WhatsApp Image 2020-05-02 at 2 39 58 AM (2)](https://user-images.githubusercontent.com/33206022/81138729-dc398b80-8f17-11ea-9f67-675976fd8bca.jpeg)
![WhatsApp Image 2020-05-02 at 2 39 58 AM (3)](https://user-images.githubusercontent.com/33206022/81138733-e065a900-8f17-11ea-8b19-597d780fa17f.jpeg)

**Comment by dihweng** [comment]
Hello
I'm also experiencing the same issues, when ever i make a request it shows Payment Successful but after that the onCancel is called instead of onSuccess  
```
onCancel={() => {console.log('cancelled')}}
```

**Comment by samie820** [comment]
@dihweng I am not quite sure why that is the case for you, but I submitted a PR that exposes a `handleWebViewMessage` method, you can use that to see the raw event being sent from the webView
