### ISSUE TITLE
Add apple pay to channels

### ISSUE THREAD

**Issue by just1and0** [just1and0/React-Native-Paystack-WebView#186]
**Is your feature request related to a problem? Please describe.**
Apple pay is now supported in inlinejs, can this be added to this package.

**Describe the solution you'd like**
nill
**Describe alternatives you've considered**
nill
**Additional context**
https://paystack.com/docs/developer-tools/inlinejs/
['card', 'bank', 'ussd', 'qr', 'eft', 'mobile_money', 'bank_transfer', ‘apple_pay’]

**Comment by opmat** [comment]
@just1and0 I opened a pull request (#189) for this

**Comment by just1and0** [comment]
Available on latest version.
