### ISSUE TITLE
how do i close or reload the webview if paystack fails to load (webview rendered in a modal), and  can i make the  webview not get rendered in a modal as it takes up the entire screen and it will be cool if  i can choose  for the  webview to be rendered in a modal or a regular view component.

### ISSUE THREAD

**Issue by sharafadeenhammed** [just1and0/React-Native-Paystack-WebView#190]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I setup the package in my React Native JS project, it seem the project has an issue with imported types in javascript.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sharafadeenhammed** [comment]
i made some changes to your work on here that reflect those changes https://github.com/sharafadeenhammed/native-customizable-paystack-webview

**Comment by just1and0** [comment]
Hi @sharafadeenhammed  ,

I noticed your project and wanted to address some concerns. While open-source projects encourage collaboration and innovation, it's important to respect the principles of the MIT license, which require proper attribution and credit to original contributors.

Copying a project, renaming it, and publishing it as a separate work without attribution undermines the efforts of the original contributors. It would be far more constructive and fair to submit a pull request (PR) to the original repository with your improvements, enabling collaboration and benefiting the wider community.

I kindly request that you either take down the project or properly credit the original contributors and consider opening a PR to share your enhancements with the community. This approach promotes fairness and aligns with the ethos of open-source development.

Looking forward to your understanding and cooperation.
