### ISSUE TITLE
WebView is no more part of the react-native core

### ISSUE THREAD

**Issue by chrisehlee** [just1and0/React-Native-Paystack-WebView#2]
Nice job overall.
For the most recent version of `react-native@60.x.x`, this is what happens.
```javascript
Invariant Violation: WebView has been removed from React Native. It can now be installed and imported from 'react-native-webview' instead of 'react-native'.
```
Is it possible to add the `react-native-webview` package as a peer dependency?
I'm open to working on this as a PR if you're unavailable.

**Comment by just1and0** [comment]
Hey, Thanks.

I'm opened to PR's. Feel free to make changes.

**Comment by chrisehlee** [comment]
Okay.

**Comment by just1and0** [comment]
If you also have time on your hands you could check out these packages below and help update. Than

**Comment by chrisehlee** [comment]
Sure will when i can.
