### ISSUE TITLE
Type Error, React. UseState is not a function

### ISSUE THREAD

**Issue by AnayoOleru** [just1and0/React-Native-Paystack-WebView#26]
![Screenshot 2020-06-07 at 6 19 52 AM](https://user-images.githubusercontent.com/37017788/83961020-2b603c80-a887-11ea-8fb2-078241f6f425.png)

I can't even view the payment screen when I navigate to the payment screen where I imported the component, I get this. When I decide to use version 2.0, I get an empty screen with only the text:

"Pay Now"

Please, is there anything I'm doing wrong. The docs seem straightaway, but is there anything else to do that is not mentioned?

**Comment by just1and0** [comment]
Hi, please do update the package to the latest version.
