### ISSUE TITLE
Unnecessary secret key requirement

### ISSUE THREAD

**Issue by cahakgeorge** [just1and0/React-Native-Paystack-WebView#37]
Paystack APIs mostly needs only the public key to identify a receiving merchant.
Having a user embed and store Paystack secret on the client side might pose some risk. Submitting a PR

**Comment by just1and0** [comment]
Hi @cahakgeorge 

I do understand the concern but adding your secret key is optional and this feature is included for experimental purposes, also there's a  **Disclaimer** in the readme that explains this risk.
