### ISSUE TITLE
Stuck at bank auth screen

### ISSUE THREAD

**Issue by surafelbm** [just1and0/React-Native-Paystack-WebView#42]
Hello,

there seems to be a problem when trying to use a card that requires a bank authorization right after you enter the card info it asks you to authenticate with the bank and you press authenticate and it leads to this page where it just gets stuck sayin "Please close this webpage to continue". this also happens with the test public key when you select the bank auth option.
i have a gif demonstrating the issue 

Environmets:
react-native :- 0.62.2
"react-native-paystack-webview": "^3.2.0"

![Screen-Recording-2020-08-08-at-4](https://user-images.githubusercontent.com/11531221/89711997-98cb3f00-d996-11ea-953b-84057d2919ab.gif)

**Comment by just1and0** [comment]
HEY, Could you show a code snippet of how you implemented this ?

**Comment by surafelbm** [comment]
no the transaction doesnt complete, onSuccess is never called.


`<PaystackWebView
          buttonText="Pay Now"
          showPayButton={false}
          paystackKey="pk_test_yt6t3..."
          paystackSecretKey="sk_test_75f"
          amount={parseInt(this.props.options.amount)}
          billingEmail={this.props.options.email}
          ActivityIndicatorColor="#01172F"
          SafeAreaViewContainer={{marginTop: 5}}
          SafeAreaViewContainerModal={{marginTop: 5}}
          refNumber={this.props.options.reference_no}
          onCancel={async (e) => {
            // handle response here
            await this.props.updatePaymentStatus({
              paymentError: true,
              paymentErrorMessage: 'Transaction was cancelled',
            });

            this.props.navigation.goBack(null);

            
          }}
          onSuccess={async (response) => {
            // console.log("PAYMENT RESPONSE : ",e)
            await this.verifyTransaction(response.data.reference)
            this.setState({loading:false})
          }}
          autoStart={true}
      />`

**Comment by ighotouch** [comment]
How do we resolve this having same issue

**Comment by ighotouch** [comment]
Also with cards that require Auth

**Comment by surafelbm** [comment]
@ighotouch still hasn't figured it out ended up using Flutterwave.

**Comment by osueke-christian** [comment]
@just1and0 this package is gaining some traction but this is a huge blocker.
Any solution I sight ???

**Comment by yinka1255** [comment]
the problem is this email in their doc paystackwebview@something.com. If you replace this email, it wont work. Try fix this pls

**Comment by Francis-nova** [comment]
I have this problem, anybody found a way around this yet ?

**Comment by nlabofa** [comment]
same here

**Comment by allindeveloper** [comment]
Hello
I'm still experiencing the same issue
when using Bank Auth

**Comment by therealgemjosh** [comment]
I keep getting this error :::Error: Unable to resolve module react-native-webview
could you pls try update the module so as to fix issue with the core react-native-webview as its marked deprecated by the core framework.

**Comment by mosoakinyemi** [comment]
Looking at this atm...sorry for the delays guys

**Comment by mosoakinyemi** [comment]
Just isolated this issue to be iOS only
Here's a snack with my implementation: https://snack.expo.io/KJMPWO2oz

Looking into this

**Comment by mosoakinyemi** [comment]
> I keep getting this error :::Error: Unable to resolve module react-native-webview
> could you pls try update the module so as to fix issue with the core react-native-webview as its marked deprecated by the core framework.

Hey @therealgemjosh thanks,
Could you share more details on your project?
- What RN version?
- Expo or Bare RN
- What version on RN-paystack-webview?

**Comment by olucodes4u** [comment]
Great tutorial, please when I hit the save button, I got this error in my terminal;   undefined Unable to resolve module react-native-paystack-webview from C:\Users\New User\Music\moneystack\src\screens\payment.js: react-native-paystack-webview could not be found within the project or in these directories:
  node_modules

Please how do I solve this?

I'm using react-native expo
and I have  "react-native-webview": "11.2.3" installed on my project already through, expo install react-native-webview

Thanks in anticipation for a timely response

**Comment by mosoakinyemi** [comment]
Resolved this in [v4.0.0-rc1](https://github.com/just1and0/React-Native-Paystack-WebView/releases/tag/v4.0.0-rc1)

**Comment by just1and0** [comment]
@all-contributors please add @surafelbm for bug

**Comment by just1and0** [comment]
@surafelbm V4.0.2 is published and I can confirm this issue has been fixed.

**Comment by codexjoshy** [comment]
this is still an issue for me .
I am using expo 45

**Comment by feisal-Codes** [comment]
this is still an issue, any work around or solutions?
