### ISSUE TITLE
Why is the paystack private key required?

### ISSUE THREAD

**Issue by ckosiegbu** [just1and0/React-Native-Paystack-WebView#43]
Great job here @just1and0. 

I'm a bit reluctant to use it because I wonder why we need to specify both public and private keys to use the control as opposed to only public keys when using paystack's own inline js. I'm extremely reluctant to transfer both keys over the wire to a client mobile app which might be able to be compromised. Is there a way to use this with just the public key?

**Comment by just1and0** [comment]
Hey @ckosiegbu ,

You can use the package with just your public key but keep in mind that your transaction won't be verified but you can do that on your backend.
Adding your secrete key will verify the payment after billing the user, tho it's not safe i felt it'd be nice to have this feature, tho it'd be removed in the future release.
