### ISSUE TITLE
Exposure of secret Key

### ISSUE THREAD

**Issue by benjamin-daniel** [just1and0/React-Native-Paystack-WebView#45]
This Project exposes the secret key when verifying the reference, this has serious security implication and as someone nefarious can use it. I advise against verifying the transaction on the client side, as verification should be done on server side.

**Comment by just1and0** [comment]
The docs clearly state this in **[Disclaimer](https://github.com/just1and0/React-Native-Paystack-WebView#disclamier)**  and this feature is being removed in a future release.
