### ISSUE TITLE
Payment in USD

### ISSUE THREAD

**Issue by vinaykr579** [just1and0/React-Native-Paystack-WebView#49]
Hello,

Is there any option to accept payment in (US Dollars).? I am unable to find currency option in the documentation. There is a option for currency in paystack payment documentations. How to use currency option in this react native package?

**Comment by parthya** [comment]
@vinaykr579 How did you solve this?

**Comment by stokkpiledev** [comment]
Please how did you solve this @vinaykr579 ?
