### ISSUE TITLE
Error: Duplicate Transaction Reference 

### ISSUE THREAD

**Issue by eakenbor** [just1and0/React-Native-Paystack-WebView#50]
When I click on the Pay Now button I get an error message: "Duplicate Transaction Reference" despite entering the correct credentials. Please can anyone help me with this? I have attached a screenshot. Also see the PaystackWebView props.

<PaystackWebView
                        buttonText="Pay Now"
                        showPayButton={true}
                        paystackKey={Config.PAYSTACK_PUBLIC_KEY}
                        amount={120000}
                        billingEmail="paystackwebview@something.com"
                        billingMobile="09787377462"
                        billingName="Oluwatobi Shokunbi"
                        ActivityIndicatorColor="green"
                        SafeAreaViewContainer={{ marginTop: 5 }}
                        SafeAreaViewContainerModal={{ marginTop: 5 }}
                        onCancel={(e) => {
                            // handle response here
                        }}
                        onSuccess={(e) => {
                            // handle response here
                        }}
                        autoStart={false}
                    />

![Screenshot_1599935585](https://user-images.githubusercontent.com/30095266/93002535-00495100-f538-11ea-8416-4a2b85aefe46.png)

**Comment by Onibenjo** [comment]
please how was this solved

**Comment by Luckae** [comment]
You could just on your own add a unique reference in your PayStackWebView like so:

refNumber={Math.floor((Math.random() * 1000000000) + 1)}

This solves the problem.

**Comment by emyduke** [comment]
Very helpful @Luckae

**Comment by Luckae** [comment]
@emyduke Nice.

**Comment by jemkob** [comment]
Thanks @Luckae

**Comment by MavDavis** [comment]
life saviors>>>>
