### ISSUE TITLE
unable to add my custom data

### ISSUE THREAD

**Issue by ossyfizy1** [just1and0/React-Native-Paystack-WebView#51]
Good morning, 

I tried integrating the "react-native-paystack-webview" on a react native app.
I found out that passing my own custom amount or changing the default {120000} to say {150000} leaves the paystack modal window loading without showing the payment options. It just keeps loading.
Love to know how to walk around this issue.
Thanks

**Comment by muhammadfaizkhan** [comment]
It also keeps me stuck on loading anyway, did you got the solution ? I didn't get and I'm near to upload this my task is about to end please help how to fix this issue.

**Comment by ossyfizy1** [comment]
I guess I switched to another payment option for it. The project was
continued by someone else. But talk directly to the customer service to
assist you further.

Regards

**Comment by muhammadfaizkhan** [comment]
Yes please or tell me the other solution for paystack payment integration
in my app.

**Comment by ossyfizy1** [comment]
Please communicate with the representatives

**Comment by just1and0** [comment]
@all-contributors please add @ ossyfizy1 for bug

**Comment by just1and0** [comment]
@all-contributors please add @ossyfizy1 for bug

**Comment by just1and0** [comment]
@ossyfizy1   V4.0.2 is published and I can confirm this issue has been fixed.

**Comment by muhammadfaizkhan** [comment]
https://www.fiverr.com/s2/e10d640412?utm_source=_Mobile
