### ISSUE TITLE
3D-S secure authentication failure

### ISSUE THREAD

**Issue by omivrex** [just1and0/React-Native-Paystack-WebView#58]
Hey guys I used this nodule in test mode it worked well but when I tried doing a life payment in my app and I get this error. "The cardholder was not authorised. This is used in 3-D Secure Authentication". I did this with a Visa card linked to my zenith Bank account. I have checked through the paystack forum but I don't see anything on how to resolve this issue. Please can someone explain why this error is occuring

**Comment by mosoakinyemi** [comment]
Hey @omivrex , sorry for the late response.
Where you able to resolve this?

**Comment by mosoakinyemi** [comment]
I can see some info on 3D-S cards
https://paystack.com/docs/guides/using_the_paystack_checkout_in_a_mobile_webview#handling-3ds-properly

**Comment by mosoakinyemi** [comment]
would look into it after work hours

**Comment by mosoakinyemi** [comment]
Sorted this out in [v4.0.0-rc1](https://github.com/just1and0/React-Native-Paystack-WebView/releases/tag/v4.0.0-rc1)

**Comment by just1and0** [comment]
@all-contributors please add @omivrex for bug

**Comment by just1and0** [comment]
@omivrex V4.0.2 is published and I can confirm this issue has been fixed.
