### ISSUE TITLE
don't use currency

### ISSUE THREAD

**Issue by Ujjalcha1** [just1and0/React-Native-Paystack-WebView#61]
i can't change currency NGN to USD

please help

**Comment by muhammadfaizkhan** [comment]
Did your component working fine ? For me it's showing loading continuously.

**Comment by Ujjalcha1** [comment]
go to node_modules > React-Native-Paystack-WebView >index.js
put it for currency change----> currency: '${props.currency}',

in package single quotes symbol are missing

**Comment by mosoakinyemi** [comment]
Will push a PR for this

**Comment by just1and0** [comment]
@all-contributors please add @Ujjalcha1  for bug

**Comment by just1and0** [comment]
@Ujjalcha1  V4.0.2 is published and I can confirm this issue has been fixed.
