### ISSUE TITLE
Pay Now Button Component not displaying in Front End

### ISSUE THREAD

**Issue by mosesegboh** [just1and0/React-Native-Paystack-WebView#78]
Hello, installed the library, but I cannot find the "Pay Now" button when I load the component on my app as displayed in the tutorial. Who can help. Is there anything extra I need to do?
Regards.

**Comment by just1and0** [comment]
Hello 👋🏾 

pay now button was taken out of V4, I’d advice referring to the docs on the use of Ref to initiate payment with pay now button [here](https://github.com/just1and0/React-Native-Paystack-WebView#usage-2---using-refs)

**Comment by just1and0** [comment]
Hello what version are you using ?

**Comment by mosesegboh** [comment]
I also get the error, "Paystack props is not defined" when I pass in "null as a parameter for the useRef code I highlighted above "as displayed in the image below;
![image](https://user-images.githubusercontent.com/56415400/129048605-af414098-f84f-4fb4-b1c5-e716631a77a7.png)

**Comment by mosesegboh** [comment]
Hello,
Thanks for the response.
 I tried it as you have stated in the code, however, I am still getting the same error on that same line of code.
I even went as far as disabling javascript validation in my vscode but the code won't compile due to that error.
Below is a screenshot of my code with the error message
![image](https://user-images.githubusercontent.com/56415400/129123437-e3dc6339-0e89-47d8-9ef7-68b1b38aba4d.png)

**Comment by just1and0** [comment]
I have tried to replicate this issue but it still works fine for me. Can we hop on a call this morning to see what the issue is, google meet. 

Ps: I won’t be free anything after 12:00pm

**Comment by mosesegboh** [comment]
Hello Tobi,
Kindly give me time and a link and will definitely be available

**Comment by just1and0** [comment]
What’s your email ?

**Comment by mosesegboh** [comment]
mosesegboh@gmail.com

**Comment by just1and0** [comment]
Just sent an invite, we can do 8:30

**Comment by mosesegboh** [comment]
ok noted

**Comment by mosesegboh** [comment]
Hi Tobi, 
I am in

**Comment by mosesegboh** [comment]
Hi Tobi,
I have sent you an invite on github.
Looking forward to hearing from you soon.
Thanks once again.
Regards.
