### ISSUE TITLE
the ref Usage is not working 

### ISSUE THREAD

**Issue by sheggietyn** [just1and0/React-Native-Paystack-WebView#80]
i wanted to use my own personal button so I tried the Ref usage in the documentation but it keeps saying unexpected token no matter what I change 

the issue is from here 

const paystackWebViewRef = useRef<paystackProps.PayStackRef>();

**Comment by sheggietyn** [comment]
i was able to solve the ref issue but these are the new problem I observed:

1 billingName: billing name does not send a billers Name to Paystack, I have tried a lot of ways it didn't work, likewise the Billing phone number too

**Comment by coolheaded1** [comment]
> i was able to solve the ref issue but these are the new problem I observed:
> 
> 1 billingName: billing name does not send a billers Name to Paystack, I have tried a lot of ways it didn't work, likewise the Billing phone number too

Kindly provide solution here....

**Comment by kvngcheerio** [comment]
Use ` const paystackWebViewRef = useRef(paystackProps.PayStackRef); ` instead of `const paystackWebViewRef = useRef<paystackProps.PayStackRef>();`

**Comment by just1and0** [comment]
I will close this and mark it as resolved.
