### ISSUE TITLE
We could not start transaction, currency not supported

### ISSUE THREAD

**Issue by asadadams** [just1and0/React-Native-Paystack-WebView#87]
We could not start transaction, currency not supported is the message i receive when trying to make payment

**Comment by webchyf** [comment]
add currency as a prop
example   <Paystack
            currency="GHS"
paystackKey="test"
paystackSecretKey="test"
billingEmail='test@gmail.com'
billingMobile='0819001274387'
billingName='Test'
channels={["mobile_money"]}
amount={'250.00'}
onCancel={(e) => {
// handle response here
}}
onSuccess={(res) => {
// handle response here
}}
ref={this.paystackWebViewRef}
/>

**Comment by vikasnhz** [comment]
Not working same error.
