### ISSUE TITLE
Webview removed from 'react-native'

### ISSUE THREAD

**Issue by deveid** [just1and0/React-Native-Paystack-WebView#9]
It complains about webview been removed from 'react-native'
@just1and0 Please change it to import WebView from 'react-native-webview'

**Comment by just1and0** [comment]
It does that because a version that supports react native 0.60 or latest hasn’t been made, I’m currently working on that, once that’s done you should be able to use it.

**Comment by deveid** [comment]
okay...I'm using it for RN 0.60 and I had to change it but nice worj

**Comment by ochui** [comment]
#10 @just1and0

**Comment by just1and0** [comment]
@deveid do make use of the latest version which now supports react-native 0.60
