### ISSUE TITLE
Unstable package

### ISSUE THREAD

**Issue by GideonAgboba** [just1and0/React-Native-Paystack-WebView#94]
The react-native-paystack-webview npm package works sometimes and just suddenly stops working. It also does not work on some devices. Is there anything I need to know?

Here's my package.json:
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-paystack-helpers": "^0.0.1",
    "react-native-paystack-webview": "^3.2.1",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^8.1.1",

This is an old project and the same can be said for my new projects with paystack if I need to keep pushing updates to fix paystack webview then this may turn out to be a serious package stability problem I guess. sometimes it's this white screen, sometimes the success callback does not fire and other times the webview does not launch at all.

**Screenshots**
![Screen Shot 2022-01-20 at 06 52 07](https://user-images.githubusercontent.com/33206022/150275709-1a746f97-a3e1-405c-961c-d1b4455999e7.png)

**Comment by just1and0** [comment]
try latest version.
